package models;
// Generated 02-mar-2021 18:27:13 by Hibernate Tools 4.3.1


/**
 * Vistaempleados generated by hbm2java
 */
public class Vistaempleados  implements java.io.Serializable {
    // Atribute
    private VistaempleadosId id;

    // Constructors
    public Vistaempleados() {}

    public Vistaempleados(VistaempleadosId id) {
       this.id = id;
    }

    // Methods (get & set)
    public VistaempleadosId getId() {
        return this.id;
    }
    
    public void setId(VistaempleadosId id) {
        this.id = id;
    }




}


