package models;
// Generated 03-mar-2021 15:58:02 by Hibernate Tools 4.3.1



/**
 * Vistaempleados generated by hbm2java
 */
public class Vistaempleados  implements java.io.Serializable {


     private VistaempleadosId id;

    public Vistaempleados() {
    }

    public Vistaempleados(VistaempleadosId id) {
       this.id = id;
    }
   
    public VistaempleadosId getId() {
        return this.id;
    }
    
    public void setId(VistaempleadosId id) {
        this.id = id;
    }




}


